### ISSUE TITLE
why add 1

### ISSUE THREAD

**Issue by yja1** [iamnotahumanbecauseiamabot/Distance-IoU-Loss-Faster-and-Better-Learning-for-Bounding-Box-Regression#1]
interArea = tf.maximum(0.0, (xB - xA + 1)) * tf.maximum(0.0, yB - yA + 1)

why +1?

**Comment by notabee** [comment]
Basically it's not required, but in my situation it was needed because I had a list which contained boxes whose difference could go zero, but I needed to include tf.maximum because otherwise the formula would lose generality. So you can remove one from there without worrying. Also see that you don't divide anywhere with zero, the main issue with these IoUs is the numerical instability so take care of that too.
